### ISSUE TITLE
Odd completer bug

### ISSUE THREAD

**Issue by saulshanabrook** [plumatic/schema#337]
I am getting an error when I try to use `complete`

```
  actual: clojure.lang.ExceptionInfo: Input to done?-max-generations-inner does not match schema: [{:individuals (not #error {
 :cause "Assert failed: (not= x +missing+)"
 :via
 [{:type java.lang.AssertionError
   :message "Assert failed: (not= x +missing+)"
   :at [schema.experimental.complete$eval16935$fn__16936$fn__16953 invoke "complete.clj" 55]}]
 :trace
 [[schema.experimental.complete$eval16935$fn__16936$fn__16953 invoke "complete.clj" 55]
  [schema.experimental.complete$eval16986$completer__17003$fn__17010$fn__17011$fn__17012 invoke "complete.clj" 89]
  [schema.spec.collection$element_transformer$fn__1197$fn__1198 invoke "collection.clj" 16]
  [schema.core.MapEntry$fn__2020 invoke "core.clj" 739]
  [schema.spec.collection$element_transformer$fn__1197 invoke "collection.clj" 16]
  [schema.spec.collection$element_transformer$fn__1197 invoke "collection.clj" 16]
  [schema.spec.collection.CollectionSpec$fn__1224 invoke "collection.clj" 47]
  [schema.experimental.complete$eval16935$fn__16936$fn__16953 invoke "complete.clj" 55]
  [schema.experimental.complete$eval16986$completer__17003$fn__17010$fn__17011$fn__17012 invoke "complete.clj" 89]
  [schema.spec.collection$element_transformer$fn__1197$fn__1198 invoke "collection.clj" 16]
  [schema.core$map_elements$iter__2045__2049$fn__2050$fn__2057 invoke "core.clj" 788]
  [schema.spec.collection$element_transformer$fn__1197 invoke "collection.clj" 16]
  [schema.spec.collection$element_transformer$fn__1197 invoke "collection.clj" 16]
  [schema.spec.collection$element_transformer$fn__1197 invoke "collection.clj" 16]
  [schema.spec.collection.CollectionSpec$fn__1224 invoke "collection.clj" 47]
  [schema.experimental.complete$eval16935$fn__16936$map_completer__16937 invoke "complete.clj" 53]
  [schema.experimental.complete$eval16986$completer__17003$fn__17010$fn__17011$fn__17012 invoke "complete.clj" 89]
  [schema.experimental.complete$complete doInvoke "complete.clj" 97]
  [clojure.lang.RestFn invoke "RestFn.java" 423]
  [search.algorithms.base_test$fn__17481$gen_with_index__17482 invoke "base_test.clj" 75]
  [search.algorithms.base_test$fn__17481 invoke "base_test.clj" 80]
```

I am trying to use it like this:

```clojure
(def Genome s/Any)
(def Traits {s/Keyword s/Num})

(def Individual {:genome Genome
                 :id s/Str
                 :traits Traits
                 :parents-ids [s/Str]})

(def Generation {:run-id s/Str
                 :index s/Int
                 :individuals [Individual]})
(c/complete {:index 1} Generation))
```

`generate` works fine on this structure, however.

**Comment by w01fe** [comment]
Thanks for the report.  This was fixed on master awhile back, I just released 1.0.5 with the fix -- sorry for the trouble.

**Comment by saulshanabrook** [comment]
@w01fe That's great, thanks for the release. I'll re-open this if I upgrade and still get the error.
